print("Selamat datang di Kalkulator Sederhana")
print("Ketik 1 untuk menghitung penjumlahan")
print("ketik 2 untuk menghitung pengurangan")
print("ketik 3 untuk menghitung perkalian")
print("ketik 4 untuk menghitung pembagian")
print("ketik 5 untuk menghitung sisa hasil bagi (modolus")
print("ketik 6 untuk menghitung pemangkatan")
A =input("Masukan pilihan anda :")
B =input("Masukan bilangan pertama :")
C =input("Masukan bilangan kedua :")
print("hasil dari 5 dijumlahkan dengan 3 adalah 9")
